# Generated by Django 5.2 on 2025-04-18 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['model'], 'verbose_name': 'Carro'},
        ),
    ]
